* IBIO input-output helpers
** Simplified I/O in Java programs
   This repository contains a set of static input-output helper
   methods written by the IBO. The copyright holder of the original
   code is IBO. Here the code has been packaged conveniently, and
   instructions have been provided for easy use.

** Installation
*** If you are using Intellij IDEA
    In Intellij IDEA, this package needs to be installed only once,
    and then you can use it in all your projects.

    Installation steps are as follows:
    1. Create a new project from version control.
    2. As project source, give 
       #+begin_example
       https://github.com/jarmohurri/ibio.git
       #+end_example
    3. Install git if asked to do that.
    4. After git has cloned the project, verify that IDEA will use an
       appropriate version of Java:
       1. Select =File -> Project structure... -> Project=.
       2. Check that a version of Java is selected in =Project SDK=.
       3. Press =OK=.
    5. Build the package jar file:
       1. Right click on file =build.xml=.
       2. Select =Add as Ant build file=.
       3. Select =Build -> ibio -> <default target>=.
    6. After the build has finished, you can close the =ibio=
       project. The package is ready to be used.

    After this, to use this package in a project:
    1. Select =File -> Project structure...=.
    2. Select =Modules=.
    3. Select =Dependencies=.
    4. Select =+ -> JARs or directories...=.
    5. This opens a file selector. Locate =ibio.jar= and select it.
    6. Select =OK=.
*** If you are using git as your own version control system
    Just add this library as a submodule of your project:
    #+begin_src sh
      git submodule add https://github.com/jarmohurri/ibio.git
    #+end_src
       
** Usage in Java
   1. Add the following line into your Java file:
      #+begin_src java
      import static ibio.Helpers.*;
      #+end_src
   2. Now the helpers are available to you without a class prefix. For example, you can directly call
      #+begin_src java
      output (156);
      #+end_src
      
** Disclaimer
   THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
   WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
   WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
   AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR
   CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
   OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
   NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
   CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
